### ISSUE TITLE
Setup docs

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#1]
The documentation can live in this repo, under the `docs` folder.

Let's use the same theme as for the other JupyterHub projects, while using the Plasma Bio logo in the top left corner:
- https://the-littlest-jupyterhub.readthedocs.io
- https://jupyterhub.readthedocs.io

The docs should be available at https://plasmabio.readthedocs.io

**Comment by pierrepo** [comment]
Hi @jtpio 
the `quantstack` team has now write access to the `doc` repo but we can indeed  use the `docs` folder in this repo.
Sphinx is indeed a good idea to handle documentation, even if I'm not a big fan of ReST :cry:

**Comment by jtpio** [comment]
Thanks @pierrepo!

I agree it ReST might not be as clear and simple as Markdown for example, but there is some benefits of using a similar stack as the other projects.

**Comment by pierrepo** [comment]
> I agree it ReST might not be as clear and simple as Markdown for example, but there is some benefits of using a similar stack as the other projects.

Fully agree! And ReST is not *that* horrible...
