### ISSUE TITLE
List in documentation files that retain the hub configuration and that need to be backed up

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#100]
Although the whole setup and configuration of TLJH is performed with ansible playbooks, it would be nice to know which files or directories of TLJH should be backed up on the server.

**Comment by pierrepo** [comment]
In the *Configuration* section, it could be nice to have the list of directories where:
- TLJH is installed
- the PlasmaBio extension is installed

**Comment by jtpio** [comment]
This will mostly be about linking to the JupyterHub and TLJH documentations:

- DB backup: https://jupyterhub.readthedocs.io/en/stable/admin/upgrading.html#backup-database-config
- TLJH installer: http://tljh.jupyter.org/en/latest/topic/installer-actions.html#what-does-the-installer-do

Also the `uninstall.yml` playbook provides some information on where things are installed.

**Comment by pierrepo** [comment]
Yes @jtpio a link to the proper TLJH doc will be sufficient ;-)
