### ISSUE TITLE
Improve user orientation within Docker container

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#107]
(New) Users might find difficult to *orient* themselves while being in a Docker container.

Within a Docker container, user home directory (`/home/foo`) is mapped to a given directory on the host (`/home/foo/plasmabio-template-python-master`).

If a user open a console in the Docker container, `pwd` will return `/home/foo`. User might worry not to find the usual listing as he could get while sshing directly on the host.

To simply that, there could be two solutions:

1. The user home directory inside the Docker container could be `/home/foo-tmp` or `/home/foo-in-docker`) instead of `/home/foo`. The user will then know he's not in his *real* home directory

2. The user home directory inside the Docker container could be the same as the directory in the host, i.e. `/home/foo/plasmabio-template-python-master`. This will reflect the same path as it is on the host. But if the user do `ls /home/foo`, he won't see anything but the `plasmabio-template-python-master` directory.

**Comment by jtpio** [comment]
Option 2 sounds like a good idea to reflect what is actually on disk.

**Comment by pierrepo** [comment]
Agreed also for option 2.

Is-it complicated to implement?

Would it be possible? Pertinent? to add a empty file called `USER_CONTENT_TEMPORARY_NOT_ACCESSIBLE` in the user directory on the Docker container. This would not exist on the host.

**Comment by jtpio** [comment]
> Is-it complicated to implement?

It should be possible by configuring `image_homedir_format_string` from `SystemUserSpawner` in the pre spawn hook: 

https://github.com/jupyterhub/dockerspawner/blob/6f7e04ce9f989e98cf99bb2a6dfa1cff96466135/dockerspawner/systemuserspawner.py#L26-L37 

> Would it be possible? Pertinent? to add a empty file called `USER_CONTENT_TEMPORARY_NOT_ACCESSIBLE` in the user directory on the Docker container. This would not exist on the host.

To mostly serve as a hint to the user that they are only seeing a subset of their files? Technically yes (a simple `touch USER_CONTENT_TEMPORARY_NOT_ACCESSIBLE` should do the trick)

Or should we consider that they will get used to the fact that by starting the `plasmabio/template-python:master` image they will only have access to `/home/foo/plasmabio-template-python-master`?

**Comment by pierrepo** [comment]
To start with, a warning file `USER_CONTENT_TEMPORARY_NOT_ACCESSIBLE` or `USER_CONTENT_NOT_ACCESSIBLE_IN_CONTAINER` could be useful.

**Comment by jtpio** [comment]
Well the files in `/home/foo/plasmabio-template-python-master` are still user data, and they are accessible from the container.

This file name might also make it sound like all files in the container are temporary.

**Comment by pierrepo** [comment]
> This file name might also make it sound like all files in the container are temporary.

Correct! Forget the warning file.

**Comment by jtpio** [comment]
Thinking about it a bit more. Maybe there could be some text on the spawn page saying that only the files corresponding to the image will be mounted from the host into the container:

![image](https://user-images.githubusercontent.com/591645/79489517-b0fc0480-801b-11ea-9596-ece7f99a06af.png)

That would require extending the template for the spawn page to add this message.

**Comment by pierrepo** [comment]
Yes. That could be a good idea but we shouldn't disturb the user with a message using image / host / mounted... Maybe we could add something like:

> Within an environment, files from your user directory will be temporary unavailable.

**Comment by pierrepo** [comment]
Still thinking out loud... and probably wrong... but would it be possible to map `/home/foo` on the host to `/home/foo` in the container, and when the container is run, create the directory `/home/foo/plasmabio-template-python-master` in the container (with all necessary files)? Then the base directory of the container will be `/home/foo` and the user will have to click (within Jupyter Lab) on `plasmabio-template-python-master` and then `materials` to access the notebooks.

**Comment by jtpio** [comment]
> Maybe we could add something like:
 
> > Within an environment, files from your user directory will be temporary unavailable.

It is available, but just a subset of it.

> would it be possible to map `/home/foo` on the host to `/home/foo` in the container

Yes, this is what `SystemUserSpawner` does by default.

> and when the container is run, create the directory `/home/foo/plasmabio-template-python-master` in the container (with all necessary files)? Then the base directory of the container will be `/home/foo` and the user will have to click (within Jupyter Lab) on `plasmabio-template-python-master` and then `materials` to access the notebooks.

All of this is definitely possible. It's true that it might be less confusing to the user if they expect all their files to be available in the container every time.

However there could be some issues with environments not working as expected if some configuration is supposed to be in the home folder. For example this is the case when installing the bash kernel without the `--sys-prefix`  flag. In that case it will be located in `/home/foo/plasmabio-template-python-master/.jupyter` but it will not be picked up if JupyterLab is started in `/home/foo`. Unless we specify `jupyter --paths` on startup. We could also imagine some non-Jupyter configuration or something install in `~/.local` too.

**Comment by jtpio** [comment]
> However there could be some issues with environments not working as expected if some configuration is supposed to be in the home folder. For example this is the case when installing the bash kernel without the `--sys-prefix` flag. In that case it will be located in `/home/foo/plasmabio-template-python-master/.jupyter` but it will not be picked up if JupyterLab is started in `/home/foo`. Unless we specify `jupyter --paths` on startup. We could also imagine some non-Jupyter configuration or something installed in `~/.local` too.

One workaround for this would be to educate the users creating the environments, to make sure that everything gets installed under the sys prefix (which should be the case most of the time).

There is also the other "drawback" that testing on Binder will not exactly look like what end users will get in the hub environment. But maybe that's ok compared to the benefit of having all files mounted into the container?

**Comment by jtpio** [comment]
(reopened to make the discussion more visible)
