### ISSUE TITLE
Set the list of admins as an Ansible variable

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#109]
For now there is only one admin test user:

https://github.com/plasmabio/plasmabio/blob/bc48a4b73c148859fa6865a086e14fd480b60c57/ansible/tljh.yml#L26

Instead we could specify the list of admins in an Ansible variable in the `hosts` file for example.

**Comment by pierrepo** [comment]
Is it possible to set *admin* users after the installation of TLJH?

**Comment by jtpio** [comment]
Yes, using `tljh-config`: http://tljh.jupyter.org/en/latest/howto/admin/admin-users.html#adding-admin-users-from-the-command-line

Do you think it would make sense to have a task to do that explicitely? Or maybe a separate playbook?

**Comment by pierrepo** [comment]
> Do you think it would make sense to have a task to do that explicitely? Or maybe a separate playbook?
Yes. A separate playbook would be nice. Could we pass the name of the user as an argument of the playbook?

**Comment by jtpio** [comment]
Ansible supports passing variables via the command line: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#passing-variables-on-the-command-line

So we should be able to pass a list of user names and then use the list in the task.

**Comment by pierrepo** [comment]
:+1:
