### ISSUE TITLE
Prepare host for multiple servers and DNS

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#122]
As for now, only one domain server is registered in `default.yml`:
```
letsencrypt_domain: dev.plasmabio.org
```
In order to support multiple servers, would it be possible to list multiple IP addresses and domains in the `hosts` file? For instance:
```
[servers]
51.68.113.AAA name_server=dev1.plasmabio.org
51.68.113.BBB name_server=dev2.plasmabio.org
```
The `name_server` variable would then be used to configure the https part.

**Comment by jtpio** [comment]
Absolutely :+1: 

The DNS is actually a user variable and should be moved outside of the `default.yml` variable file.

We should also move the `letsencrypt_email` and default to `''` if it is not specified.
