### ISSUE TITLE
Remove aptitude installation from Ansible playbooks

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#145]
Ansible playbooks `docker.yml` and `tljh.yml` have a task to install `aptitude`. The default installer on Ubuntu is `apt` and shouldn't need `aptitude`.
`aptitude` was indeed required and this was a know bug of Ansible 8: https://github.com/ansible/ansible/issues/56832
Maybe we could remove the tasks that install `aptitude` in  `docker.yml` and `tljh.yml` playbooks (as done in `utils.yml`).
To be extra cautious, we could also enforce Ansible >= 2.9 in the installation:
```
python -m pip install ansible>=2.9
```

What are your thoughts on this @jtpio?

**Comment by jtpio** [comment]
If it can simplify the playbooks then why not.

> we could also enforce Ansible >= 2.9 in the installation

2.9 is fairly recent, but can be installed via `pip` so it should be ok to require it.

**Comment by jtpio** [comment]
Fixed by #149.
