### ISSUE TITLE
Create folders using the name of the environment

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#148]
For now, the name of the folders correspond to the name of the underlying Docker image.

Instead we could use the display name added in https://github.com/plasmabio/tljh-repo2docker/pull/7 to name the folders.

**Comment by pierrepo** [comment]
:+1:

**Comment by jtpio** [comment]
We should also check how to handle the uniqueness of the display names.

For now the user defined "Name of the environment" is just a display name. For the name of the Docker image we still use `plasmabio/template-python:master`.

Maybe we could use the custom name as the name of the Docker image, so it will also be shown in the output of `docker ps`. That would require using lowercase characters.

In the end the folder name could look like this: `2020-m1-python-a1b2c3` or ``2020-m1-python-a1b2c3`.

**Comment by jtpio** [comment]
> Maybe we could use the custom name as the name of the Docker image, so it will also be shown in the output of `docker ps`. That would require using lowercase characters.

This change would go in https://github.com/plasmabio/tljh-repo2docker.

**Comment by pierrepo** [comment]
So at the end, we could have the same name for:
- the env,
- the Docker image,
- the directory in which files are pushed.

That is appealing.

Having the name as lowercase only seems a small drawback.
