### ISSUE TITLE
Docker Compose vs TLJH

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#2]
Ideally it would be great to use an existing JupyterHub distribution such as [The Littlest JupyterHub](https://tljh.readthedocs.io).

The current recommendations for using TLJH are listed in https://tljh.jupyter.org/en/latest/topic/whentouse.html:
- 1-100 users
- single machine deployment
- Ubuntu 18.04+

Having a full Docker setup can have several benefits, such as defining the entire stack in a `docker-compose.yml`, combining it with provisioning tools such as [Ansible](https://docs.ansible.com/ansible/latest/modules/docker_compose_module.html), and using other existing Docker tools for monitoring and maintenance.

This issue is mostly intended to weight the pros and cons of the two approaches to lower the maintainbility efforts in the long run.

Other Docker based setups:
- https://github.com/jupyterhub/jupyterhub-deploy-docker
- https://github.com/defeo/jupyterhub-docker

Related:
- https://github.com/jupyterhub/the-littlest-jupyterhub/issues/75
- http://words.yuvi.in/post/the-littlest-jupyterhub/

**Comment by pierrepo** [comment]
One issue I'm worried about is the following: could we *really* (I mean efficiently) use docker within another docker container?
We spoke that user envs could be handled by docker container. If the jupyter-hub itself lives in a docker container, it means that user envs will be created in docker containers from within a docker container.

**Comment by jtpio** [comment]
With the current minimal configuration the Docker socket is mounted from the host into the `hub` container:

https://github.com/plasmabio/plasmabio/blob/2270e762481749ae3a149635818256dc24dda833/docker-compose.yml#L16

And the user containers end up being at the same level as the hub container on the host machine:

```
$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                    NAMES
f0109bf5d632        jupyter/scipy-notebook   "tini -g -- start-no…"   9 seconds ago       Up 7 seconds        8888/tcp                 jupyter-jtp-jupyter_scipy-notebook-python
c2f10d6ac803        plasmabio-hub            "jupyterhub"             22 seconds ago      Up 21 seconds       0.0.0.0:8000->8000/tcp   hub
```

**Comment by pierrepo** [comment]
OK @jtpio thanks for the explanations.
Could please add a comment before the line you mentionned above and in the `docker-compose.yml` file to remind us (and others) that
>  the user containers end up being at the same level as the hub container on the host machine

Do you feel it will scale well (with up to 50 or more docker container)?

**Comment by jtpio** [comment]
For sure :+1: 

This can depend on the specs of the machine of course. The best way would be to test it, by either creating 50+ named servers for a single user (each server will have its own container), or use a script to simulate real world activity.

**Comment by pierrepo** [comment]
@jtpio I read *somewhere* that Docker could involve security issues (I do not know which actually).
Could a user *escape* from his own container and gain access to the JupyterHub container since they are at the same level on the host computer?

**Comment by jtpio** [comment]
This could indeed be an issue when exposing the socket to the user containers (gaining root access on the host).

But in this case the Docker socket is only mounted into the hub container, and not into the user containers.

**Comment by pierrepo** [comment]
> But in this case the Docker socket is only mounted into the hub container, and not into the user containers.

I'm not skilled enough to undestand this :face_with_head_bandage:  We will discuss this matter IRL.
The main idea is to keep the all thing as safe as possible.

**Comment by jtpio** [comment]
No problem.

What I meant is that in the hub container the socket is available (which is used to spawn servers with the `DockerSpawner`):

```
root@c2f10d6ac803:/srv/jupyterhub# ls /var/run/
docker.sock  lock  motd.dynamic  mount  systemd  utmp
```

But in the single user containers it is not:

```
jovyan@f0109bf5d632:~$ ls /var/run/
lock/  mount/  systemd/  utmp
```

**Comment by pierrepo** [comment]
So I guess it's a good news!

**Comment by jtpio** [comment]
After discussing the pros and cons of the two approaches, we came to the conclusion that developing a plugin for TLJH sounds like a good solution for now.

### Pros for a `docker-compose` setup

- Few differences between the local and the deployed setups
- Ability to pin Docker images and use newer hub versions
- Some documentation in the following projects, although "less maintained":
  - https://github.com/jupyterhub/jupyterhub-deploy-docker
  - https://opendreamkit.org/2018/10/17/jupyterhub-docker/
  - https://github.com/defeo/jupyterhub-docker

### Pros for TLJH

- Active project
- 1 of the 2 popular JupyterHub distributions: https://jupyterhub.readthedocs.io/en/stable/index.html#distributions
- Well documented and tested
- Same target OS (Ubuntu 18.04)
- Easily extendable via plugins
- Arguably simpler and less custom configuration to maintain
