### ISSUE TITLE
Add new environments (docker images) to the deployment

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#23]
There should be a clear process (and documentation) on how to add new environments to the hub installation.

These environments will come from repositories containing the materials, and be built using `repo2docker`:

Example: https://github.com/plasmabio/materials-example

**Comment by jtpio** [comment]
The images are for now specified in the plugin config:

https://github.com/plasmabio/plasmabio/blob/58b0e22a3285309e02ad200830c50b57f7157c4f/tljh-plasmabio/tljh_plasmabio/__init__.py#L8-L11

**Comment by jtpio** [comment]
Maybe something similar to this could work: https://github.com/ideonate/repo2dockerspawner

**Comment by jtpio** [comment]
Ideally we will still want to have the configuration (list of environments) versioned in a repository, to track the changes and make it easy to redeploy on a new version.

**Comment by jtpio** [comment]
@pierrepo thinking out loud here: what do you think between these two ways of managing user environments?

### UI

User environments (Docker images) could be managed via the JupyterHub UI directly. They would be accessible to admin users only. 

Something similar to the existing admin interface but instead it would list the repositories and have buttons to add, remove and update the images on the server directly.

![image](https://user-images.githubusercontent.com/591645/76983323-7e3bef00-693d-11ea-8fa5-a55a42b9002b.png)

Then the environments will show up in this list when the user will want to start a server:

![image](https://user-images.githubusercontent.com/591645/76983420-aaf00680-693d-11ea-87ca-c84382e51509.png)

This requires building some custom logic to manage this, as well as a custom JupyterHub page and a way to store the list (local file / db), but can be added to the TLJH plugin. There is also a [list of JupyterHub services examples](https://github.com/jupyterhub/jupyterhub/tree/master/examples) to have an idea of what services look like.

### Ansible and version controlled

Alternatively the list of environments can be listed in a `yaml` file. A separate ansible playbook would pick up the file and build the images on the server using `repo2docker`.

Adding, removing or updating an environment would mean editing this file and running the playbook to deploy it.

**Comment by pierrepo** [comment]
Hi @jtpio 
Thank you for the brain storming.
Teachers need a simple as possible way to add (delete & update) envs. The first option seems the best and the most accessible.

**Comment by jtpio** [comment]
I played a bit with the second option (Ansible), but running `repo2docker` considerably increases the deploy time, which can lead to a connection loss too. So that's not optimal.
