### ISSUE TITLE
Pre pull Docker images

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#25]
At the moment, the first time a user server is started on a new VM, the Docker image must be entirely pulled, which slows down the spawn process quite a bit. 

This is related to https://github.com/plasmabio/plasmabio/issues/23 and how we want to manage the different environments. Given a list of environments, we could decide to pull them all when they are updated or a new one is added.

**Comment by pierrepo** [comment]
Will it look like a kind of post-hook from the GitHub repo?

**Comment by pierrepo** [comment]
Last time we spoke about a kind of light graphical interface where the user could configure a new environment by providing the url of a new repo (that contains the description of the env). Could we add a button to refresh the environment (rebuild the docker image)?

**Comment by jtpio** [comment]
We can take (at least) two approaches:

- Build the images on the server directly with `repo2docker` and passing the URL of the repo. Once they are built they are directly available
- Use a registry (DockerHub, GitHub) to store the images. Add CI will push the new images when the repos are updated. These images will need to be pulled from the registry down to the server, either using a hook indeed or by updating a central config file and re running.

It really depends how we want to manage the different environments (#23) and how we want them to be updated (or always use the latest).

**Comment by pierrepo** [comment]
As of today, option 1 seems the easiest to me.

I'm not a big fan of adding an extra layer of CI right now.

**Comment by jtpio** [comment]
OK good, then let's go for that.

And let's see in #23 how user environments should be managed and updated.
