### ISSUE TITLE
Missing host makes ansible playbook fail

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#29]
Following the documentation to deploy [PlasmaBio with Ansible](https://plasmabio.readthedocs.io/en/latest/install/ansible.html), I encounter an issue with the following command:
```
$ ansible-playbook all.yml -u ubuntu
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [all] ******************************************************************************************************************************************************************
skipping: no hosts matched

[...]
```

The `hosts` file has been modified accordingly to reflect the new server IP address. Ansible documentation says `hosts` file is usually in `/etc/ansible/hosts` but that does not seem relevant here.

**Comment by jtpio** [comment]
Fixed by #30.
