### ISSUE TITLE
Add diagram

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#3]
There should be a diagram (created with graphviz / cytoscape?) in the documentation to show how the different components interact with each other.

Also this deployment should make clear what the requirements and the scopes are (single machine, Docker).

**Comment by pierrepo** [comment]
A good old svg edited with Inkscape good also do the trick.

**Comment by Scaburet** [comment]
This  sure would help non-geek newbies (such as me) to understand what you guys are talking about ! :-D

**Comment by jtpio** [comment]
Will create a simple one once the docs (#1) are setup!

**Comment by jtpio** [comment]
@Scaburet @pierrepo the docs now have an overview diagram: https://docs.plasmabio.org

It still needs some iterations for example to show how the environments are built. But in the meantime don't hesitate to open issues if something is not clear or needs to be updated!

**Comment by pierrepo** [comment]
Thanks @jtpio :tada:
