### ISSUE TITLE
Remove default hosts file?

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#31]
I was wondering if it's a good idea to keep a default `hosts` file that is marked as *modified* by git when adapted for the current server.

Could we ask the user to create a `hosts` file with the following content:
```
[servers]
<servers IP address>
```

and move the remaining lines
```
[servers:vars]
ansible_python_interpreter=/usr/bin/python3
```
elsewhere, probably in `ansible/vars/default.yml`?

Does it seem reasonable?

**Comment by jtpio** [comment]
We can indeed remove it for now.

The inventory can be passed via the command line, and there is only one server to target at a time.

**Comment by pierrepo** [comment]
I still think a `hosts` file is a good practice (and we will soon have 2 servers) but we do not necessarily need to track this file with git.
