### ISSUE TITLE
Cull idle servers

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#37]
Servers that are inactive for given amount of time can be culled, to free resources on the server.

Culling can be enabled with TLJH: https://tljh.jupyter.org/en/latest/topic/idle-culler.html#configuring-the-idle-culler

**Comment by pierrepo** [comment]
Seems a good idea. What could be a reasonable time out?

**Comment by jtpio** [comment]
This can be tweaked easily, but 1 hour sounds reasonable.
