### ISSUE TITLE
Show the current image in the top bar

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#38]
As mentioned in https://github.com/jtpio/jupyterlab-topbar/issues/35, we could make use of the `jupyterlab-topbar-text` extension to show to the users the image they are currently using.

This means adding the `jupyterlab-topbar-text` to the dependencies here: https://github.com/plasmabio/template-python/blob/master/postBuild

And define a `pre_spawn_hook` in the plugin to update the lab settings.

Something that would look like the following:

![image](https://user-images.githubusercontent.com/591645/77162842-2a501800-6aad-11ea-9731-b17920ca1f9a.png)

**Comment by pierrepo** [comment]
That is definitely a good idea to remind user in which environment/container he's working in.
:+1:

**Comment by pierrepo** [comment]
@jtpio do you have any idea how `jupyterlab-topbar-text` could be aware of the environment name?

Could you do a demo with `template-python`? I'll try to propagate it with other kernels.

**Comment by jtpio** [comment]
We'll probably want to place this in the entrypoint, to be able to update the name of the image dynamically on server startup.

Something similar to the approach mentioned in https://github.com/jtpio/jupyterlab-topbar/issues/35#issuecomment-580713551, by creating the settings file in the `.jupyter/lab/user-settings/jupyterlab-topbar-text` of the environment folder.
