### ISSUE TITLE
Encouter error in ansible deployment rule

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#53]
While testing the deployment rule with Ansible on a clean WM, I encountered the following error:

```
$ ansible-playbook all.yml -i hosts -u ubuntu
[...]

TASK [Upgrade the tljh-plasmabio plugin] ********************************************************************************************************************************
fatal: [51.68.115.253]: FAILED! => {"changed": true, "cmd": "/opt/tljh/hub/bin/pip3 install --upgrade git+https://github.com/plasmabio/plasmabio@master#\"egg=tljh-plasmabio&subdirectory=tljh-plasmabio\"", "delta": "0:00:00.006162", "end": "2020-03-24 09:59:00.496351", "msg": "non-zero return code", "rc": 127, "start": "2020-03-24 09:59:00.490189", "stderr": "/bin/sh: 1: /opt/tljh/hub/bin/pip3: not found", "stderr_lines": ["/bin/sh: 1: /opt/tljh/hub/bin/pip3: not found"], "stdout": "", "stdout_lines": []}
...ignoring

[...]
```

No idea if it's an important error or not.

**Comment by pierrepo** [comment]
Final Ansible output was:
```
PLAY RECAP **************************************************************************************************************************************************************
51.68.XXX.YYY              : ok=21   changed=15   unreachable=0    failed=0    skipped=0    rescued=0    ignored=1 
```

**Comment by jtpio** [comment]
Yes, it corresponds to this task, which is used to upgrade the plugin if it is already installed:

https://github.com/plasmabio/plasmabio/blob/0d849cefb45ea57d8d3e0c4a6434c3a682ec24aa/ansible/tljh.yml#L20-L23

However it is marked with `ignore_errors: yes` to the playbook doesn't fail on the first run. And it logs `...ignoring` in the task output.

Later on, we can add tags and improve the playbook to have more control on this.

**Comment by pierrepo** [comment]
OK. Thanks. But is it *good* or *bad* if this task failed?

If it's not very important, maybe you could add a note in the documentation explaining it does not matter.

**Comment by jtpio** [comment]
It's not bad, and should only fail on a fresh install.

You could indeed add documentation about this, or use Ansible conditions to only run the task if the plugin is already installed.

This is related to this issue: https://github.com/jupyterhub/the-littlest-jupyterhub/issues/400
