### ISSUE TITLE
Wording: image or environment?

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#62]
Speaking out loud here in order to use a consistent naming across the documentation and the code base.

For now the docs mention "environments" to talk about "User environments". In the code they were initially referred to as "images" as in "Docker image". But it would be better to unify the naming of this.

Is there any preference between these two options? It sounds like "environment" is more user friendly than "image".

**Comment by pierrepo** [comment]
I would tend to keep both.

- `Environments` for end users and the general documentation.
- `(Docker) images` for the admin and the code.

We could write a warning at the beginning of the documentation explaining for the more advanced user and tech-savy people that what we call `environment` are actuel Docker images.

Do you think it's still confusing?

**Comment by jtpio** [comment]
> We could write a warning at the beginning of the documentation explaining for the more advanced user and tech-savy people that what we call `environment` are actuel Docker images.

There is now some mentions of this in the new "User Environments" section in the documentation: https://docs.plasmabio.org/en/latest/environments/index.html

Maybe that's enough? Otherwise we can definitely iterate on this to make it more clear.

**Comment by pierrepo** [comment]
>Maybe that's enough?

This is very good.
