### ISSUE TITLE
Cancel pending build

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#64]
A user could have added an image by mistake or entered the wrong `ref`.

There should be a "Cancel" button that would stop the `repo2docker` container currently building the image.

**Comment by pierrepo** [comment]
I believe, this more a "nice to have" feature than a "must have" one.

If a user add an image with the wrong reference, he can wait for the image to be built and than remove it. As a matter of fact, I'm a bit afraid to intervene to much with the `repo2docker` container...

**Comment by jtpio** [comment]
Good. For now the interface doesn't have any button for the pending builds, so we could leave it like this.

![image](https://user-images.githubusercontent.com/591645/78060065-3086a400-738b-11ea-9cf1-e352c2b2569a.png)


> As a matter of fact, I'm a bit afraid to intervene to much with the `repo2docker` container...

That would need require finding the right repo2docker container and stop it.

**Comment by pierrepo** [comment]
> That would indeed require finding the right repo2docker container and stop it.

![](https://media.giphy.com/media/s4Q3geM5T1XCo/giphy.gif)

**Comment by jtpio** [comment]
OK so let's close this then.

We can reconsider later if needed.
