### ISSUE TITLE
Clear the dialogs

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#65]
The previous input text in the "Add Image" dialog should be cleared when shown to the user:

![image](https://user-images.githubusercontent.com/591645/78056407-5f018080-7385-11ea-889b-697c3aa406ad.png)

**Comment by pierrepo** [comment]
Maybe you could replace "Add image" by "Create environnement"?

On the left of the first input field, you could add "URL of the repository".
On the left of the second input field, you could add "Reference (commit)" with a default and a placeholder set to "master"
