### ISSUE TITLE
Add a simple monitoring tool

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#70]
Depending on the tool, it could be installed using the Ansible playbooks, or as a dependency to the TLJH plugin.

For now we could consider two simple ones. By simple it means they just need to be installed with almost zero configuration.

- [Cockpit](https://cockpit-project.org/), as suggested by @pierrepo 
- [Glances](https://nicolargo.github.io/glances), which might be a bit more minimal but can be installed with pip.

Another thing to consider is whether they should be accessible via the JupyterHub UI. And in that case restrict access to admin users only.

**Comment by jtpio** [comment]
Cockpit could be an interesting choice, as it gives a nice overview of the Docker images and running containers:

![image](https://user-images.githubusercontent.com/591645/78789116-fc276f00-79ac-11ea-9672-b0a2785c185a.png)

**Comment by pierrepo** [comment]
Yes. And authentication is PAM-based.

**Comment by pierrepo** [comment]
I don't know if cockpit could be "plugged" into JupyterHub, i.e. through the same web interface.

If not, cockpit could be accessible at port 8080.

**Comment by jtpio** [comment]
Maybe a link in the navbar to open Cockpit in a new browser tab would work?

**Comment by pierrepo** [comment]
Yes, only visible to admins?

**Comment by jtpio** [comment]
Yes that would make more sense if only admins have access to it.
