### ISSUE TITLE
Set the resource limits per Docker image environment?

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#72]
Should the memory and cpu limits be configured when adding a new image?

They would then show as two new columns in the list of environments:

![image](https://user-images.githubusercontent.com/591645/78239171-ae5ac480-74dd-11ea-9487-c68d3bfdfb69.png)

If not specified they would correspond to the default limits (for instance 2GB  / 2 cpus).
 
This information could also be stored as a label on the image when it is created: https://github.com/plasmabio/plasmabio/blob/35f771db6f1dd53c644c05a17146c01e27311744/tljh-plasmabio/tljh_plasmabio/builder.py#L36

The limits would then be assigned to the spawner using the `pre_spawn_hook` by fetching the value from the label.

**Comment by pierrepo** [comment]
Oups, yes, you're totally right! RAM and CPU limit should be defined upon image creation (with default values  of 2 GB RAM and 2 CPUs).

Regarding the naming, I'm afraid the env name might be lengthy (but why not). For instance, the env name could be (using available envs on the above screenshot):
`template-bash-3706666-2-2`
For the ref, we could used the 7 first characters of the hash like GitHub is doing.

**Comment by jtpio** [comment]
For now the name of the image is created automatically to avoid invalid characters. But we could also imagine having a text field next to the repo URL where a custom (shorter) name could be specified.

> For the ref, we could used the 7 first characters of the hash like GitHub is doing.

That would work for git commit hashes, for example by doing something like `ref[:7]`. But repo2docker also accept tags and branches as ref, which could be a problem if they are used and then trimmed down to 7 characters.
