### ISSUE TITLE
Autorefresh build env page

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#74]
Upon building of a new env, the build icon is spinning forever, even after the env is actually built and available:
![image](https://user-images.githubusercontent.com/733861/78252318-f2a48f80-74f2-11ea-8d53-9002acd5553a.png)

A manual refresh of the page updates correctly the icon:
![image](https://user-images.githubusercontent.com/733861/78252398-110a8b00-74f3-11ea-906b-28b7d7cb33f0.png)

Maybe we could autorefresh the webpage every 5 seconds or so.

**Comment by jtpio** [comment]
The page can already be refreshed manually (F5 or Ctrl-R) to get the new status.

I'm a bit hesitant about the auto-refresh (especially if it refreshes the whole page), as it is often disruptive.

**Comment by pierrepo** [comment]
Agree! An alternative solution is proposed in issue #75

**Comment by pierrepo** [comment]
> The page can already be refreshed manually (F5 or Ctrl-R)

I usually do not refresh manually a web page after having submitted a form to avoid re-submission ;-) 

But it is perfectly fine if one tells me I'm allowed to
