### ISSUE TITLE
Environment build process takes long

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#75]
The process of image building performed by `repo2docker` can take some time. Depending on the performance of the machine and the complexity of the env, it can take a lot of time (at the user scale).

For instance, for the https://github.com/plasmabio/template-r env on a demo 2-core VM, it took 16 minutes. 

We should tell the user that everything is fine.

One solution is to display (or offer to display) the build log, as discussed in issue #60 

An additional solution could be to display a message in place of the "Remove" button or bellow the URL of the repo, such as "*Environnement is under construction. It could take up to several minutes. Please be patient.*" or something equivalent.

**Comment by jtpio** [comment]
> An additional solution could be to display a message in place of the "Remove" button or bellow the URL of the repo, such as "_Environnement is under construction. It could take up to several minutes. Please be patient._" or something equivalent.

This sounds good :+1: 

For reference there is a mention to slow builds in the Troubleshooting section of the docs: https://docs.plasmabio.org/en/latest/troubleshooting/index.html#the-environment-is-very-slow-to-build

**Comment by pierrepo** [comment]
In relation with issue #74 , if we believe an automatic is not needed, we can also add a message encouraging the user to regularly update this page.

**Comment by pierrepo** [comment]
Maybe we could print a warning/alert message on top of the page, each time an environment is buillding with the following statement:
> At least one environnement is under construction. 
> It could take up to several minutes. Please be patient. Why not having a cup of tea or coffee?
> Do not hesitate to regularly refresh this page to update the build status of environments."

**Comment by jtpio** [comment]
A note at the top of the page when an image is building sounds good.

We can even embed an explicit "Reload the page" link, that would trigger a refresh of the page when clicking on it.
