### ISSUE TITLE
Kernels seem inactive

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#76]
After building a new env and  running a new server, user can run the Jupyter Lab env but kernels do not look alive.
For instance:
![image](https://user-images.githubusercontent.com/733861/78253525-cdb11c00-74f4-11ea-8a7e-ca4dae9a1876.png)

Running cells are on the `[*]` status forever...

**Comment by jtpio** [comment]
This is most likely a side effect of having HTTPS enabled but accessing the server using the IP.

We can consolidate the documentation to be able to test without HTTPS and the DNS setup (not recommended so no the default).
