### ISSUE TITLE
Traefik and named servers

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#8]
Moved from https://github.com/plasmabio/plasmabio/pull/6#issuecomment-592466901.

There seems to be an issue with the routing of named server when using Traefik as a proxy: jupyterhub/traefik-proxy#91

Related fix: jupyterhub/jupyterhub#2957

This would require bumping the version in the Dockerfile when the fix lands: https://github.com/plasmabio/plasmabio/blob/master/hub/Dockerfile

**Comment by pierrepo** [comment]
Maybe we could wait to meet IRL before going any further with Traefik?

I'd like to be sure to understand what exactly are its pros and cons.

**Comment by jtpio** [comment]
The built-in support for Let's Encrypt is quite useful.
Also being able to start it in its own container helps to decouple the hub from the proxy and make the deployment more robust.

Happy to reconsider that at some point, as switching back to the default `configurable-http-proxy` (https://github.com/jupyterhub/configurable-http-proxy) should be quite straightforward.

**Comment by jtpio** [comment]
For now it is still possible to reach the named server by manually adding a `/` at the end of the URL.

**Comment by jtpio** [comment]
This is now fixed in https://github.com/jupyterhub/traefik-proxy/pull/96.

Since TLJH uses [`jupyterhub-traefik-proxy==0.1.*` to define the dependency](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/d0118e9d7b424cdde06ba90931e1ff2943de0bb6/setup.py#L21), rerunning the Ansible playbook will pickup the latest minor version.

![named-server-redirect](https://user-images.githubusercontent.com/591645/78116521-b5fa6a80-7404-11ea-8e90-d6837199d414.gif)
