### ISSUE TITLE
Removing an environment when servers are running

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasmabio#83]
At the moment it is not possible to remove an environment when a user server (Docker container) is running with the Docker image that corresponds to the environment to remove.

User servers can be stopped by admin users via the Admin panel. However the Admin panel doesn't show which image / environment is being used by the user.

This should be mentioned in the docs: https://docs.plasmabio.org/en/latest/environments/remove.html

**Comment by jtpio** [comment]
An alternative would be to add this information to the admin panel, which could look like this:

![image](https://user-images.githubusercontent.com/591645/78803298-1cf8c000-79bf-11ea-8eb7-fca259696f5b.png)

(`jupyterhub/singleuser` is the default image for DockerSpawner)

**Comment by pierrepo** [comment]
Yes. Good idea.
