### ISSUE TITLE
Memory and CPU limit selector should floored integers

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#99]
When creating new environment, we can define memory and CPU limit.
The default selector (up/down arrow) allows a large variety of values. One should constrain them:
- Memory limit. Step: 1. Lower value: 1.
- CPU limit. Step: 1. Lower value: 1.

**Comment by jtpio** [comment]
It could make things simpler indeed.

However decimal values are useful when testing on small servers, for example with 2 cpus and 4GB of RAM.
